export const rareColors = {
  Common: "gray",
  Promo: "gold",
  Rare: "blue",
  "Rare Holo": "#4b8bb4",
  "Rare Holo EX": "red",
  "Rare Holo GX": "green",
  "Rare Holo V": "orange",
  "Rare Ultra": "black",
  Uncommon: "teal",
};

export const typeColors = {
  Normal: "gray",
  Fire: "red",
  Water: "#26B7D4",
  Lightning: "#DFDA4F",
  Electric: "#DFDA4F",
  Grass: "#A8F35C",
  Ice: "cyan",
  Fighting: "orange",
  Poison: "purple",
  Ground: "brown",
  Flying: "skyblue",
  Psychic: "pink",
  Bug: "lime",
  Rock: "sienna",
  Ghost: "indigo",
  Dragon: "#d4af37",
  Dark: "darkgray",
  Steel: "silver",
  Fairy: "magenta",
  Colorless: "silver",
};
